[package]
name = "Atom_Simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
glfw = "0.55.0"
gl = "0.14.0"
geo = "0.28.0"
nalgebra-glm = "0.18.0"
rand = "0.8.5"
statrs = "0.16.0"
lazy_static = "1.4.0"
